"""
Django settings for Snaplytics project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent
load_dotenv(dotenv_path=ROOT_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0=kbtc$oh2+zm^y)xx94s5s5$in+u+o-di9tz$1_=md+ie9ncd"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["10.0.2.2", "192.168.1.53", "127.0.0.1", "localhost"]

CORS_ALLOW_ALL_ORIGINS = True
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "backend",
    "endpoints",
    "rest_framework",
    "rest_framework.authtoken",
    "recommender",
    "corsheaders",
]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "postgres"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5501",
    "http://localhost:5501",
]

REST_FRAMEWORK = {
    # Single string, not a list
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",

    # Authentication belongs in its own key
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],

    "PAGE_SIZE": 20,
}

# Email (defaults to console backend unless SMTP vars are provided)
if os.getenv("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() in ("1", "true", "yes")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@snaplytics.local")

ROOT_URLCONF = "Snaplytics.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Snaplytics.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Outbound email (coupon compose, etc.) ───────────────────────────────────
# Prefer HEIGEN_SMTP_*; fall back to standard Django-style EMAIL_* / DEFAULT_FROM_EMAIL
# so one .env can match typical hosting docs. Strip spaces from app passwords (Gmail
# displays them in groups of 4; SMTP auth uses the 16 chars without spaces).
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = (
    os.getenv("HEIGEN_SMTP_HOST", "").strip()
    or os.getenv("EMAIL_HOST", "").strip()
    or "smtp.gmail.com"
)
_smtp_port = os.getenv("HEIGEN_SMTP_PORT", "").strip()
if not _smtp_port:
    _smtp_port = os.getenv("EMAIL_PORT", "587").strip()
EMAIL_PORT = int(_smtp_port or "587")
if os.getenv("HEIGEN_SMTP_USE_TLS") is not None:
    EMAIL_USE_TLS = (
        os.getenv("HEIGEN_SMTP_USE_TLS", "1").strip().lower()
        not in ("0", "false", "no")
    )
else:
    _tls = os.getenv("EMAIL_USE_TLS", "true").strip().lower()
    EMAIL_USE_TLS = _tls not in ("0", "false", "no")
EMAIL_HOST_USER = (
    os.getenv("HEIGEN_SMTP_USERNAME", "").strip()
    or os.getenv("EMAIL_HOST_USER", "").strip()
)
_raw_pw = (
    os.getenv("HEIGEN_SMTP_PASSWORD", "").strip()
    or os.getenv("EMAIL_HOST_PASSWORD", "").strip()
)
EMAIL_HOST_PASSWORD = _raw_pw.replace(" ", "")
HEIGEN_SMTP_FROM_EMAIL = (
    os.getenv("HEIGEN_SMTP_FROM_EMAIL", "").strip()
    or os.getenv("DEFAULT_FROM_EMAIL", "").strip()
    or EMAIL_HOST_USER
)
DEFAULT_FROM_EMAIL = HEIGEN_SMTP_FROM_EMAIL or "webmaster@localhost"
HEIGEN_SMTP_SENDER_NAME = os.getenv("HEIGEN_SMTP_SENDER_NAME", "").strip()
