# Generated by Django 5.2.8 on 2025-11-30 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('applies_to', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('gcash_payment', models.FloatField(blank=True, null=True)),
                ('cash_payment', models.FloatField(blank=True, null=True)),
                ('discounts', models.TextField(blank=True, null=True)),
                ('session_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_source', models.CharField(blank=True, max_length=255, null=True)),
                ('is_first_time', models.BooleanField(blank=True, null=True)),
                ('previous_session_counts', models.IntegerField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('consent', models.TextField(blank=True, null=True)),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('promo_price', models.FloatField(blank=True, null=True)),
                ('promo_price_condition', models.TextField(blank=True, null=True)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('inclusions', models.JSONField(blank=True, null=True)),
                ('included_portraits', models.JSONField(blank=True, null=True)),
                ('freebies', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StagingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_checksum', models.CharField(max_length=255)),
                ('raw_row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('canonical_data', models.JSONField()),
                ('processing_status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_quantity', models.IntegerField()),
                ('addon_price', models.FloatField()),
                ('total_addon_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='backend.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.package'),
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField()),
                ('avg_booking_value', models.FloatField()),
                ('booking_frequency', models.FloatField()),
                ('renewed_within_365', models.BooleanField()),
                ('total_spent', models.FloatField()),
                ('preferred_package_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.customer')),
            ],
        ),
    ]
