# Generated by Django 5.2.11 on 2026-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_customer_package"),
    ]

    operations = [
        migrations.RenameField(
            model_name="renewal",
            old_name="renewed_within_365",
            new_name="renewed_within_366",
        ),
        migrations.AlterField(
            model_name="addon",
            name="applies_to",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="addon",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="booking",
            name="session_status",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="acquisition_source",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_number",
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="full_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="instagram_handle",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="category",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="preferred_package_type",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="stagingbooking",
            name="file_checksum",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="stagingbooking",
            name="file_name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="stagingbooking",
            name="processing_status",
            field=models.CharField(default="PENDING", max_length=31),
        ),
    ]
