# Generated by Django 5.2.11 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_staffprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="profile_photo_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
