# Generated by Django 5.2.11 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_alter_staffprofile_profile_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
