# Generated by Django 5.2.11 on 2026-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_staffprofile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
