# Generated by Django 5.2.11 on 2026-05-09 11:17

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_staffprofile_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesos_per_point_earn', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=12)),
                ('pesos_per_point_redeem', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=12)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Loyalty settings',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='loyalty_points_credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=12),
        ),
    ]
