# Generated by Django 5.2.11 on 2026-05-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_customer_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='dev_mode',
            field=models.BooleanField(default=False, help_text='Elevated Dev tier (e.g. permanent purge in Internal Records); applies on top of STAFF/ADMIN/OWNER.'),
        ),
    ]
